### ISSUE TITLE
Produzir Roadmap do projeto

### ISSUE THREAD

**Issue by josutk** [Desenho2018-1/pan-pan#10]

**Comment by Rdlenke** [comment]
@josutk @fabiolamfleury Vocês acham que utilizar as milestones do git como um roadmap seria uma ideia ruim?

**Comment by fabiolamfleury** [comment]
@Rdlenke É uma boa

**Comment by josutk** [comment]
@Rdlenke concordo

**Comment by josutk** [comment]
Não será nada documentado em relação ao roadmap? se ja foi documentado onde posso encontrar?

**Comment by Rdlenke** [comment]
A que documentação se refere? Existe uma breve explicação de porque as milestones serão utilizadas como o roadmap [aqui][milestones], e no [documento de metodologias utilizadas][metodologia].

O roadmap em si pode ser encontrado na página de [milestones][p-milestones] do projeto. Podemos fazer uma imagem pra representar se quiser, ou ainda, linkar essa página na sidebar.

[p-milestones]:https://github.com/Desenho2018-1/pan-pan/milestones
[milestones]:https://github.com/Desenho2018-1/pan-pan/wiki/Configura%C3%A7%C3%A3o-de-Software-e-Pol%C3%ADticas-do-Reposit%C3%B3rio#711-definir-milestone
[metodologia]:https://github.com/Desenho2018-1/pan-pan/wiki/Metodologia-Utilizada#scaled-agile-framework-safe

**Comment by josutk** [comment]
era exatamente a isso que me referia, estou fechando a issue
