### ISSUE TITLE
Finalizar MoSCoW da elicitação

### ISSUE THREAD

**Issue by alaxalves** [Desenho2018-1/pan-pan#12]
https://github.com/Desenho2018-1/pan-pan/wiki/Elicita%C3%A7%C3%A3o-dos-Requisitos#todo-terminar-esse-moscow

**Comment by josutk** [comment]
o que falta para terminar?

**Comment by Rdlenke** [comment]
@josutk Nada. Ela tá na pipe de revisão, não?
