### ISSUE TITLE
Alinhar processo e Artefatos 

### ISSUE THREAD

**Issue by josutk** [Desenho2018-1/pan-pan#14]
Alinhar documentos existentes no projeto, devido o fato de existir informações desconexas  na elaboração dos artefatos.

**Comment by Rdlenke** [comment]
No documento de [Engenharia de Requisitos](https://github.com/Desenho2018-1/pan-pan/wiki/Engenharia-de-Requisitos), que explica como aplicamos as técnicas no nosso projeto, acredito que a técnica de RichPicture esteja sendo explicada muito a fundo em seu conceito, mas pouco relacionado a como procuramos usá-lá pro projeto. 

No mesmo documento, a explicação da técnica de Prototipação também está muito conceitual, não definindo qual será utilizada no projeto.

**Comment by josutk** [comment]
Sobre o RichPicture que falta entendimento sobre os conceitos para entender melhor como será utilizado, quando ao protoitipo acabo de subir como será utilizado.
