### ISSUE TITLE
Produzir Processo do Projeto

### ISSUE THREAD

**Issue by Rdlenke** [Desenho2018-1/pan-pan#2]

**Comment by Rdlenke** [comment]
O processo foi produzido, porém deve ser atualizado de acordo com os novos subprocessos que estão e que irão ser executados. @fabiolamfleury @pablodiegoss @josutk

**Comment by josutk** [comment]
Falta algo para ser concluido no processo?

**Comment by Rdlenke** [comment]
@josutk Não. Eu só não fechei ainda porque volta e meia me vem algo a mente e eu dou uma atualizada, mas já está finalizado.

**Comment by josutk** [comment]
Posso considerar fechado?

**Comment by Rdlenke** [comment]
@josutk Ainda não. Falta indicar o uso do protótipo de alta fidelidade.
