### ISSUE TITLE
Produzir Diagrama de Caso de Uso - Manter Usuário

### ISSUE THREAD

**Issue by josutk** [Desenho2018-1/pan-pan#26]
Para editar o diagrama de caso de uso devem ser realizados os seguintes passos:

1.  Entrem na ferramenta _draw.io_.
2.  No drive da equipe, façam o download do arquivo _casodeuso.xml_.
3. importem o arquivo no _draw.io_.

**Comment by Rdlenke** [comment]
Como meu conhecimento sobre diagramas de caso de uso é muito raso, eu acreditei que esse diagrama seria um pouco mais complexo e indicaria melhor as interações entre o usuário e o site. O diagrama deve realmente ser simplificado assim? Se sim, ele é realmente relevante para o projeto?

**Comment by josutk** [comment]
Não tenho certeza sobre o que você falou, mas vou dar uma estudada melhor sobre o diagrama e também irei mudar a ferramenta na qual foi feito.

**Comment by josutk** [comment]
O diagrama foi atualizado.

**Comment by josutk** [comment]
@Rdlenke  as mudança no diagrama de caso de uso remete ao que havia dito no comentário anterior?, se sim irei fechar a issue

**Comment by Rdlenke** [comment]
Eu estou com uma dúvida porque o diagrama está demasiadamente simples. Eu não sei qual é o nível de detalhamento que um caso de uso tem que ter. 

Quando eu pensei nos diagramas por feature, eu pensei que o detalhamento ia ser maior. Por exemplo, no caso de Manter Usuário:

"Realizar Login"
"Visitar página de perfil"
"Atualizar dados"
"Excluir conta"

Porém ao mesmo tempo que você encontra na internet diagramas detalhados, encontra alguns muito simples. Eu gostaria de saber dos outros membros como eles acham que deveria ser.

**Comment by josutk** [comment]
posso detalhar mais, mas como saber até que ponto detalhar?

**Comment by Rdlenke** [comment]
@josutk Aí é uma pergunta muito boa. Você pode detalhar pensando nas histórias que vamos fazer (que não sejam técnicas), e o relacionamento entre elas. Aí acho que você pode fazer só da feature, se começar a ficar muito grande. Se ficar muito pequeno aí eu não sei, haha.
