### ISSUE TITLE
Produzir documento de arquitetura

### ISSUE THREAD

**Issue by josutk** [Desenho2018-1/pan-pan#27]

**Comment by Rdlenke** [comment]
O documento foi criado. Faltam os seguintes pontos:

Restrições do sistema.
Versão das linguagens/frameworks que serão utilizados.
Imagem ilustrando o MVC.
Explicação de como o Spring implementa o MVC.
Explicação do diagrama de sequência.

**Comment by rodrigocam** [comment]
Explicação do diagrama de sequência **done**

**Comment by josutk** [comment]
Foi atualizado o documento de arquitetura:
Restrições do sistema: foi inidicado que deve ser extensivel em um framework
Foi adicionado as versões das tenologias utilizadas
Imagem representativa do mvc 
Explicação reve de como o spring implmenta o mvc mais um link para um documentação bem completa em relação ao seu pleno funcionamento.
