### ISSUE TITLE
Produzir Diagrama de Pacotes - Manter Usuário

### ISSUE THREAD

**Issue by Rdlenke** [Desenho2018-1/pan-pan#28]

**Comment by josutk** [comment]
Levando em consideração a arquitetura do projeto até o momento foi elaborado o que vem a ser a versão inicial do diagrama de pacotes.

**Comment by Rdlenke** [comment]
Acredito que fazer o diagrama de pacotes foi uma escolha ruim. Queria mudar pra um diagrama de componentes. Eu mesmo posso fazer.
EDIT: Pensando bem, vi que o diagrama de componentes serve pra mostrar as interfaces de um componente. Provavelmente nossa arquitetura é pouco componentizada, então esse diagrama teria pouco valor.

**Comment by josutk** [comment]
independente de ser feito um diagrama de componentes, o de pacotes não seria necessario fazer um diagrama de pacotes para demonstrar a visão da arquitetura mvc implementada no projeto ?

**Comment by pablodiegoss** [comment]
Acho que a camada de View deve ser melhor descrita para que fique explícito os componentes do React, mas não necessariamente separar em um diagrama de componentes,  podem ser feitos no mesmo diagrama já que o de pacotes está bem simples.

**Comment by pablodiegoss** [comment]
Diagrama atualizado
