### ISSUE TITLE
Criar Conta

### ISSUE THREAD

**Issue by Rdlenke** [Desenho2018-1/pan-pan#31]
Eu, como usuário, desejo criar minha conta no **Pan-Pan** para ter disponível as funcionalidades do site.

O usuário deve ser capaz de visitar a página de cadastro do Pan-Pan, e realizar seu cadastro, com uma confirmação que ele foi efetuado com sucesso.

Pontos: 5

**Comment by fabiolamfleury** [comment]
Depende da criação do ambiente de testes para finalização, validações no front e no back end, e uma possível implementação de segurança
