### ISSUE TITLE
Criação de banda

### ISSUE THREAD

**Issue by Rdlenke** [Desenho2018-1/pan-pan#35]
Eu, como usuário, desejo criar a minha banda no sistema **Pan-Pan** para poder gerenciá-la.

**Comment by rodrigocam** [comment]
Lembrete: atualizar diagrama de classes, model Band. Retirar campo city.

**Comment by rodrigocam** [comment]
Lembrete: atualizar o diagrama de classes, apagar controller de User e Band, tendo em vista que as controllers desempenham um papel diferente do imaginado pelo grupo. Adicionar classes handlers para Usuário e Banda. Link referência para handlers -> https://docs.spring.io/spring-data/rest/docs/current/reference/html/#_writing_an_annotated_handler
