### ISSUE TITLE
Produzir Documento de Políticas do Repositório

### ISSUE THREAD

**Issue by Rdlenke** [Desenho2018-1/pan-pan#4]

**Comment by pablodiegoss** [comment]
https://github.com/Desenho2018-1/pan-pan/wiki/Configura%C3%A7%C3%A3o-de-Software-e-Pol%C3%ADticas-do-Reposit%C3%B3rio
Documento criado, será atualizado conforme as novas ferramentas e ambiente para o projeto sejam definidos
