### ISSUE TITLE
Criar página para criação de conta

### ISSUE THREAD

**Issue by Rdlenke** [Desenho2018-1/pan-pan#41]
- [x] Criar página para criação de conta no **Pan-Pan**.
* Nome de usuário
* Email
* Senha
* Cidade
* Estado
* Idade
* Instrumentos tocados pelo usuário

**Comment by josutk** [comment]
Foi seguido o protótipo para a criação da pagina de cadastro, não está  completamente fiel ao protótipo pois ainda falta muito conhecimento da minha parte quanto ao uso do react, porem acredito eu que para o primeiro ponto de controle está em um nível aceitável.

**Comment by hugonxc** [comment]
Foi necessário alteração nos campos do front para se adequar ao diagrama de classe.As mudanças também foram adotas no protótipo. Ficando com os seguintes campos:
- Nome
- Email
- Data de nascimento
- Instrumentos tocados pelo usuário
- Estado
- Cidade
- Username
- Senha
