### ISSUE TITLE
Enviar email de confirmação de cadastro para o usuário

### ISSUE THREAD

**Issue by Rdlenke** [Desenho2018-1/pan-pan#43]
Criar maneira de enviar um email de confirmação de cadastro para o usuário. O usuário deve ser ativado no momento que confirmar o cadastro no link do email.

**Comment by rodrigocam** [comment]
Atualmente a funcionalidade está finalizada, restando realizar os testes e uma pequena refatoração nas mensagens de sucesso ou falha das requisições e algum tratamento de exceção.
