### ISSUE TITLE
Produzir Diagrama de Classe - Manter Banda

### ISSUE THREAD

**Issue by Rdlenke** [Desenho2018-1/pan-pan#44]

**Comment by Rdlenke** [comment]
Como descrito na issue #49, o diagrama será integrado ao diagrama de classes já existente, e englobado ao diagrama de pacotes.

**Comment by Joranhezon** [comment]
Vou começar a trabalhar nisso agora

**Comment by Joranhezon** [comment]
Pessoal, fiquei muito na dúvida em algumas coisas. 
- Primeiro: como eu faço pra relacionar Membros com banda? Seria controller com controller e model com model, ou apenas uma relação das duas?
- Segundo: Como represento uma lista de membros? Que no caso seria para banda.
- Terceiro: Não consegui abstrair muito os atributos de banda. Pensei nas músicas(tinham falado do repertório, mas acho que isso seria uma outra classe sozinha.)

Ficou assim por enquanto:
![diagramaclasse](https://user-images.githubusercontent.com/20938170/38314305-3ced0f8a-37fc-11e8-9e01-6426522aa9ed.png)

**Comment by Rdlenke** [comment]
@Joranhezon No primeiro ponto: eu acho que as models vão ter relação, mas a controller de banda só teria relação com banda. Pela model de banda você conseguiria pegar os dados dos integrantes.
No segundo ponto, acredito que você pode representar com um atributo List<User> bandMembers, ou algo assim. Talvez os slides da última aula ajudem nisto.
No terceiro, eu acho que você vai ter o nome da banda, estilo musical. Talvez alguma data de criação, a lista de membros. Posteriormente vamos ter mais atributos, como os setlists relacionados.

**Comment by Joranhezon** [comment]
Dei uma arrumada, ficou assim:
![diagramaclasse3 1](https://user-images.githubusercontent.com/20938170/38322635-63a18dbc-3811-11e8-8667-a620078f43c3.png)

O que acham?
