### ISSUE TITLE
Reorganizar kanban

### ISSUE THREAD

**Issue by fabiolamfleury** [Desenho2018-1/pan-pan#67]
Reorganizar o quadro kanban, mantendo ele apenas para histórias de usuário, pensar se outros quadros serão feitos para colocar feature e épico

**Comment by Rdlenke** [comment]
@fabiolamfleury O Zenhub permite criar mais de um quadro?

**Comment by fabiolamfleury** [comment]
Eu realmente não sei, mas no project tem como, seria ruim usar o project pra feature e épico e história de usuário no zenhub? Fica inviável ficar tudo junto, vou dar uma olhada no zenhub se da pra fazer

**Comment by Rdlenke** [comment]
Eu fiz o que você falou, Fabíola. No entanto, o ZenHub ainda continua agregando todas as issues do projeto no board. Eu não sei se dá pra desabilitar isso, mas em todo caso, o ideial seria não utilizarmos o Kanban do Zenhub e utilizarmos apenas o dos projetos.

Os diferentes kanbans podem ser encontrados no seguinte [zelda](https://github.com/Desenho2018-1/pan-pan/projects).

**Comment by fabiolamfleury** [comment]
Perfeito
