### ISSUE TITLE
Produzir diagrama NFR Framework

### ISSUE THREAD

**Issue by fabiolamfleury** [Desenho2018-1/pan-pan#7]

**Comment by josutk** [comment]
O documento foi revisado por @josutk, para melhor leitura do documento será adicionado legenda.

**Comment by pablodiegoss** [comment]
No requisito de manutenibilidade deveríamos ter um outro requisito não funcional, a qualidade do código que será atendida pelas nossas métricas e plano de qualidade.
O que acham?

**Comment by Rdlenke** [comment]
@pablodiegoss Acho ótimo.

**Comment by fabiolamfleury** [comment]
Vou atualizar agora 👍

**Comment by fabiolamfleury** [comment]
O diagrama NFR foi atualizado de acordo com a sugestão do @pablodiegoss e os épicos e features enablers foram criados a partir dele.
