### ISSUE TITLE
Produzir Diagrama de Classes - Manter Usuário

### ISSUE THREAD

**Issue by Rdlenke** [Desenho2018-1/pan-pan#8]
O diagrama de classes do projeto provavelmente vai ser produzido de acordo com as [Features]() elicitadas.

**Comment by Joranhezon** [comment]
Fiz uma primeira versão do que acredito será a classe User.

Explicando um pouco dos atributos que escolhi:
- Separei o nome do usuário em first e last, de maneira que seja obrigatório o usuário colocar um nome e um sobrenome. Essa solução pode não ser a ideal, pois estou me baseando em formulários de sites e redes sociais grandes. Dessa maneira, é possível que apenas no Frontend exista essa separação, e a partir dai juntamos as duas strings para ter apenas um atributo no banco. Porém, isso também tem suas desvantagens, algo a ser discutido;
- Adicionei os atributos age e city, de maneira que seja possível encontrar pessoas próximas ao usuário. Nesse pensamento, foi colocado o atributo role, que armazenará se o usuário é guitarrista, vocalista, etc;
- O atributo active é um booleano para decidir se a conta do usuário está ativa ou não.

Sobre os métodos:
- Coloquei apenas os métodos principais, no momento. Não foquei em nenhum que fosse relacionado com banda, pois ainda não temos tal classe definida;
- No método signIn coloquei como entrada apenas os atributos mais importantes. Tomei essa decisão baseada em uma conversa que tive com o professor Maurício em Tec Prog. Ele me disse que é melhor ter formulários menores para cadastro, pois os usuários ficam com preguiça de preencher os mais extensos. Por isso, melhor deixar as informações secundárias para serem preenchidas quando o usuário sentir necessidade.


![diagramaclasse](https://user-images.githubusercontent.com/20938170/38166601-bba7979e-34fc-11e8-8248-9164db8fbf5f.png)

**Comment by Rdlenke** [comment]
@Joranhezon, achei de boa o diagrama. Os atributos acho que no momento vão ser esses mesmo, mas tenho uma dúvida em relação aos métodos.

Nós vamos usar o MVC, e no caso a classe User seria uma model. Eu senti falta de uma Controller no diagrama, dizendo quais seriam os endpoints que o cara vai acessar pra fazer as operações. Algo do estilo:

UserController
- profile();
- editProfile(); (POST)
- deleteAccount(); (POST)
- signIn(); (POST) & (GET)
- logOUt(); (POST)

Isso pensando que o usuário poderia editar/deletar a sua conta na própria página de perfil.

Tendo isso em mente, eu tenho outra dúvida: pensando que vamos ter as controllers, o método de login/logout ficaria localizado na própria model do usuário? Eu não sei muito bem como funciona em web, mas não me recordo de ver esses métodos nas models em outros projetos.

**Comment by josutk** [comment]
disponibiliza no drive do grupo o diagrama, para que não exista mais de uma versão edital para o grupo

**Comment by Joranhezon** [comment]
Fiz o upload dos dois arquivos em uma pasta chamada diagram de classes lá no drive.

@Rdlenke faz sentido o que tu falou, mas ai eu fiquei na dúvida aqui. Como que se representa o relacionamento da model com a controller? Até dei uma fuçada aqui no que meus GPP's fizeram, mas eles só tinham feito model, no caso. Por via das dúvidas eu os deixei separados. No caso, assim:
![diagramaclasse](https://user-images.githubusercontent.com/20938170/38173793-1951499c-359a-11e8-984c-05137027abf9.png)
![diagramaclassecontroller](https://user-images.githubusercontent.com/20938170/38173794-1971f2d2-359a-11e8-909c-5c6ef3a99a53.png)

E sobre os métodos logIn e logOut, geralmente se cria uma classe (ou uma helper) só pra lidar com autenticação, então no caso ficaria em outro lugar mesmo.

**Comment by josutk** [comment]
@Joranhezon o diagrama de classes é usado para representar as classes com seus relacionamentos nesse caso entre a model e a controller seria uma associação(acredito eu), com uma seta saindo da model e indo para a controller que significa que os objetos da model podem ser instanciados na controller, então seria apenas um diagrama com essas duas classes fazendo essa relacionamento que indiquei se eu estiver realmente correto.

**Comment by Joranhezon** [comment]
@josutk não fez muito sentido pra mim, porque não achei que tinha que nossa arquitetura impactasse no jeito que a gente vai representar as classes. Ai achei meio estranho do jeito que ficou, mas é tóis. A gente tira essa dúvida com ela depois.

Ficou assim:
![diagramaclasse2 0](https://user-images.githubusercontent.com/20938170/38174095-76c7b2b0-359e-11e8-85cf-99ba1002636e.png)
