### ISSUE TITLE
Diagramação inconsistente no Composite 

### ISSUE THREAD

**Issue by alaxalves** [Desenho2018-1/pan-pan#88]
As relações de agregação estão erradas.

https://github.com/Desenho2018-1/pan-pan/wiki/GoF#implementa%C3%A7%C3%A3o-no-projeto-pan-pan

**Comment by pablodiegoss** [comment]
@alaxalves Pablo Diego Silva da Silva:
A diagramação foi feita separada do diagrama de classes, acabou ficando errado as relações. O arquivo do astah está no drive

**Comment by fabiolamfleury** [comment]
Atualizações feitas nos diagramas tanto na página do GoF quanto na página de diagrama de classe

**Comment by alaxalves** [comment]
@fabiolamfleury Maravilha, vou fechar a issue.
