### ISSUE TITLE
Descrição da metodologia Utilizada

### ISSUE THREAD

**Issue by josutk** [Desenho2018-1/pan-pan#9]
Temos na wiki como é o processo, mas não existe descrição de como é nossa metodologia
@josutk

**Comment by rodrigocam** [comment]
Revisado por @rodrigocam

**Comment by josutk** [comment]
Voltei pra review pois eu havia pedido a @fabiolamfleury revisar principalmente em relação ao requisitos do projeto

**Comment by fabiolamfleury** [comment]
Eu tinha dado uma olhada e esqueci de mexer de dar o feedback, acho que ficou legal a parte dos requisitos, e você ter colocado os spikes foi algo bem importante
